[package]
name = "apidom-ns-json-schema-2020-12"
version = "0.1.0"
edition = "2024"

[dependencies]
apidom-ast = { path = "../apidom-ast" }
apidom-ns-json-schema-2019-09 = { path = "../apidom-ns-json-schema-2019-09" }
