use crate::minim_model::Element;

/// Trait generated by the `BuildFromElement` derive macro
/// Implementations should construct `Self` from a `minim_model::Element`.
pub trait BuildFromElement: Sized {
    /// Attempt to build `Self` from an Element. Returns `None` if the element
    /// does not conform to the expected structure.
    fn build_from_element(el: &Element) -> Option<Self>;
} 