[package]
name = "apidom-gen"
version = "0.1.0"
edition = "2024"
# build = "build.rs"

[dependencies]
regex = "1.11.1"
serde = { version = "1.0", features = ["derive"] }
validator = { version = "0.20.0", features = ["derive"] }

[build-dependencies]
serde_json = "1.0"
convert_case = "0.6"
